name: Tidy Swan
title: Senior-level content designer for hire
description: Improving websites and digital services with words.
show_downloads: false
google_analytics: UA-25073272-6
theme: jekyll-theme-cayman
