title: Tidy Swan
description: Product Owner and Content Strategist | Tidy Swan

url: http://tidyswan.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 0

navigation:
 - title: Home
   url: /
 - title: Consultancy
   url: /consultancy/
 - title: Contracting
   url: /contracting-cv/
 - title: eBook Creation
   url: /ebook-creation/
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: 
   twitter: 
   facebook: 
   email:

google_analytics: "UA-25073272-6"
