title: Danny Chadburn
description: Content, just how you like it

url: http://danny.chadburn.co.uk
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 0

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: 
   twitter: 
   facebook: 
   email: danny@chadburn.co.uk

google_analytics: "UA-25073272-6"
