title: Tidy Swan
description: Content, copy, and more

url: http://tidyswan.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 0

navigation:
 - title: Content Services
   url: /index.html
 - title: Copy
   url: /headline-copy
 - title: Creative
   url: /creative-content-campaigns
 - title: Structure
   url: /content-structure
 - title: Data
   url: /content-data-models
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: 
   twitter: 
   facebook: 
   email: hello@tidyswan.com

google_analytics: "UA-25073272-6"
