title: Tidy Swan
description: Content, Copywriting, IA, Data | Tidy Swan

url: http://tidyswan.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 0

navigation:
 - title: Headline Copywriting
   url: /headline-copywriting
 - title: Content Architecture
   url: /content-structure
 - title: Content Marketing
   url: /creative-content-campaigns
 - title: Content Data
   url: /content-data-models
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: 
   twitter: 
   facebook: 
   email:

google_analytics: "UA-25073272-6"
